name: Build/Release
on: [push, pull_request]

permissions:
  contents: write

env:
  NeosPath: "${{ github.workspace }}/neos_install/" #see neos-modding-group/neos-plugin-setup-action
  BUILD_TYPE: "CICD"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Setup build environment
        uses: neos-modding-group/neos-plugin-setup-action@master
        #TODO: check for possible caching of neos build env
      - name: Download NeosModLoader and Harmony
        run: |
          mkdir -p "${NeosPath}/nml_libs" "${NeosPath}/nml_mods" "${NeosPath}/Libraries"
          cd "${NeosPath}/nml_libs" && wget "https://github.com/neos-modding-group/NeosModLoader/releases/latest/download/0Harmony.dll"
          cd "${NeosPath}/nml_mods" && wget "https://github.com/mpmxyz/NeosAssetImportHook/releases/latest/download/NeosAssetImportHook.dll"
          cd "${NeosPath}/Libraries" && wget "https://github.com/neos-modding-group/NeosModLoader/releases/latest/download/NeosModLoader.dll"
      - name: Lint
        run: dotnet format --verbosity detailed --verify-no-changes ./NeosMassImportPacker.sln
      - name: Build binaries, create release directory structure, calculate checksums
        run: |
          dotnet build ./NeosMassImportPacker.sln --configuration Release

          mkdir ./release
          
          mv ./NeosMassImportPacker/bin/Release/net462/win-x64/NeosMassImportPacker.dll ./release/NeosMassImportPacker.dll
          
          sha256sum ./release/**
      - name: Upload artifacts
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main' # only publish workflow artifacts for pushes to main or tags
        uses: actions/upload-artifact@v3
        with:
          name: NeosMassImportPacker
          path: |
            ./release/NeosMassImportPacker.dll
          if-no-files-found: error
      - name: Create release draft
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./release/NeosMassImportPacker.dll
          draft: true
